[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_mint_nft_demo = "sEVXzgRND6bkGiWz2uV1j6NTm85egusBwkHUfQaJLMo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
